### PR TITLE
Enable blackfire

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by lyrixx** [comment]
\o/

**Comment by GuGuss** [comment]
:+1:

**Comment by GuGuss** [comment]
@lyrixx Time to switch to PHP 7.1 now :) And even PHP 7.2 as soon as Blackfire supports it.

**Comment by GuGuss** [comment]
Hum, forget it, I didn't see this was legacy...

**Comment by lyrixx** [comment]
:)

**Pull request closed without merging**
